- name: Deploy Antivirus Scanner
  hosts: all
  become: True
  gather_facts: True
  roles:
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
    - antivirus
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
