- name: Deploy edX Ecommerce Worker
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_NEWRELIC: False
  roles:
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
    - ecomworker
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE
    - role: hermes
      HERMES_TARGET_SERVICE: 'ecomworker'
      when: ECOMMERCE_WORKER_HERMES_ENABLED
