---
- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE: True
    COMMON_SECURITY_UPDATES: yes
    SECURITY_UPGRADE_ON_ANSIBLE: true

  roles:
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
    - jenkins_build
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE
      tags:
        - newreliconly
