- name: Deploy Journals
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_DATADOG: False
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'journals'
    JOURNALS_ENABLED: True
    JOURNALS_SANDBOX_BUILD: False
  roles:
    - aws
    - role: nginx
      nginx_default_sites:
        - journals
    - journals
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE
