- name: Deploy edX Notes API
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_NEWRELIC: True
  roles:
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
    - role: nginx
      nginx_sites:
        - edx_notes_api
    - edx_notes_api
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE
    - role: hermes
      HERMES_TARGET_SERVICE: 'edx_notes_api'
      when: EDX_NOTES_API_HERMES_ENABLED

