- name: Deploy worker
  hosts: all
  become: True
  gather_facts: True
  roles:
    - aws
    - role: edxapp
      celery_worker: True
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: minos
      when: COMMON_ENABLE_MINOS
