- name: Deploy xserver
  hosts: all
  become: True
  gather_facts: True
  vars:
    serial_count: 1
  serial: "{{ serial_count }}"
  roles:
    - aws
    - role: nginx
      nginx_sites:
      - xserver
    - xserver
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: hermes
      hermes_target_service: 'xserver'
      when: XSERVER_HERMES_ENABLED
